name: Build and Push Docker Image

on:
    push:
        branches: [ main ]
        paths:
            - 'Dockerfile'
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - '.github/workflows/pytest.yml'
    pull_request:
        paths:
            - 'Dockerfile'
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - '.github/workflows/pytest.yml'
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:              
            version: "0.7.14"

        - name: Install the project
          run: uv sync --locked --group test

        - name: Run tests       
          env:
            PYTHONPATH: src
            MODEL_PATH: tests/test_lgbm_model_v1.txt
          run: uv run pytest
  build-and-push:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/forecast-model-api:latest

