name: Python Tests

on:
    push:
        branches: [ main ]
        paths:
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - '.github/workflows/pytest.yml'
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - '.github/workflows/pytest.yml'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:              
                version: "0.7.14"

            - name: Install the project
              run: uv sync --locked --group test

            - name: Run tests       
              env:
                PYTHONPATH: src
                MODEL_PATH: tests/test_lgbm_model_v1.txt
              run: uv run pytest